modLoader="javafml" #mandatory
loaderVersion="[34,)"
license="GNU LESSER GENERAL PUBLIC LICENSE Version 2.1"

[[mods]]
modId="unexperienced"
version="2.0.0b"
displayName="Unexperienced"
displayURL="https://www.curseforge.com/minecraft/mc-mods/unexperienced"
updateJSONURL="https://raw.githubusercontent.com/SmileycorpMC/Unexperienced/1.19/update.json"
credits="Smileycorp"
authors=""
description="Disables XP Drops"