modLoader="javafml" #mandatory
loaderVersion="[34,)"
license="GNU LESSER GENERAL PUBLIC LICENSE Version 2.1"

[[mods]]
modId="unexperienced"
version="1.1.0"
displayName="Unexperienced"
displayURL="https://www.curseforge.com/minecraft/mc-mods/unexperienced"
credits="Smileycorp"
authors=""
description="Disables XP Drops"